### ISSUE TITLE
Rock/Paper/Scissors _GAME PROJECT

### ISSUE THREAD

**Issue by gfonseca18** [an-jorge/Learning-Kotlin#1]
For the first project game can be **Rock/Paper/Scissors**
So what do you think? @an-jorge 

Check the link
[https://pt.wikipedia.org/wiki/Pedra,_papel_e_tesoura](url)

**Comment by an-jorge** [comment]
I think it´s a good idea.

Não conheço as regras do jogo mais vou dar uma olhada, obrigado pelo link

**Comment by an-jorge** [comment]
You´re can start with the game?
@gfonseca18

**Comment by gfonseca18** [comment]
#### Here’s my idea

**1.** I´ll create a new function to choose one of “Rock,Paper or Scissors”
**2.** Ask to the user for their choice.
**3.** Show the result on console

@an-jorge

**Comment by an-jorge** [comment]
Me parece bom
It´s time to code!
