### ISSUE TITLE
EX.19 – Sorteando um item da Lista

### ISSUE THREAD

**Issue by an-jorge** [an-jorge/Learning-Kotlin#3]
### 19 – Sorteando um item da Lista

 @gfonseca18 dê uma olhada no exercício.
19 – Sorteando um item da Lista

**Comment by gfonseca18** [comment]
> ### 19 – Sorteando um item da Lista
> @gfonseca18 dê uma olhada no exercício.
> 19 – Sorteando um item da Lista

Yeah! can be.
Mão na roda

**Comment by gfonseca18** [comment]
Exercício proposto

**Comment by an-jorge** [comment]
Bingo!
